import type {
  ActivityItem,
  KpiDatum,
  MarketplaceProduct,
  RemediationPlan,
  SoilReport,
} from "./types";

export const kpiData: KpiDatum[] = [
  {
    id: "sites",
    label: "Active Remediation Sites",
    value: "12",
    delta: "+2 this month",
    deltaTone: "positive",
    icon: "activity",
  },
  {
    id: "carbon",
    label: "Total Carbon Offset",
    value: "1,284 t",
    delta: "+14.8%",
    deltaTone: "positive",
    icon: "leaf",
  },
  {
    id: "analyses",
    label: "Soil Analyses",
    value: "86",
    delta: "18 pending review",
    deltaTone: "neutral",
    icon: "flask",
  },
  {
    id: "savings",
    label: "Estimated Remediation Savings",
    value: "₹42.8L",
    delta: "vs. conventional excavation",
    deltaTone: "neutral",
    icon: "coins",
  },
];

export const recentReports: SoilReport[] = [
  {
    id: "r1",
    analysisId: "PS-20481",
    siteName: "Dimapur Industrial Estate",
    soilType: "Loamy",
    contaminants: ["Lead", "Diesel"],
    toxicity: "Moderate",
    status: "Blueprint Ready",
    updatedLabel: "Today",
    consultant: "T. Zhimomi",
  },
  {
    id: "r2",
    analysisId: "PS-20477",
    siteName: "Kohima Industrial Zone",
    soilType: "Clay",
    contaminants: ["Arsenic"],
    toxicity: "Critical",
    status: "Needs Review",
    updatedLabel: "Yesterday",
    consultant: "R. Kikon",
  },
  {
    id: "r3",
    analysisId: "PS-20465",
    siteName: "Mokokchung Fuel Depot",
    soilType: "Sandy",
    contaminants: ["Diesel"],
    toxicity: "Moderate",
    status: "Monitoring",
    updatedLabel: "2 days ago",
    consultant: "A. Longkumer",
  },
  {
    id: "r4",
    analysisId: "PS-20452",
    siteName: "Dhansiripar Tannery Cluster",
    soilType: "Silty",
    contaminants: ["Chromium", "Cadmium"],
    toxicity: "Critical",
    status: "Needs Review",
    updatedLabel: "3 days ago",
    consultant: "T. Zhimomi",
  },
  {
    id: "r5",
    analysisId: "PS-20438",
    siteName: "Wokha Cement Yard",
    soilType: "Mixed / Fill",
    contaminants: ["Lead", "Petroleum hydrocarbons"],
    toxicity: "Moderate",
    status: "Blueprint Ready",
    updatedLabel: "5 days ago",
    consultant: "R. Kikon",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "a1",
    title: "Blueprint generated",
    site: "Dimapur Industrial Estate",
    timeLabel: "10 minutes ago",
    icon: "blueprint",
  },
  {
    id: "a2",
    title: "Soil reassessment uploaded",
    site: "Kohima Industrial Zone",
    timeLabel: "2 hours ago",
    icon: "upload",
  },
  {
    id: "a3",
    title: "Remediation plan updated",
    site: "Mokokchung Fuel Depot",
    timeLabel: "Yesterday",
    icon: "update",
  },
  {
    id: "a4",
    title: "Flagged for consultant review",
    site: "Dhansiripar Tannery Cluster",
    timeLabel: "3 days ago",
    icon: "review",
  },
];

export const remediationPlans: RemediationPlan[] = [
  {
    id: "p1",
    siteName: "Dimapur Industrial Estate",
    status: "Active",
    currentPhase: "Mycoremediation",
    estimatedCompletion: "Mar 2027",
    consultant: "T. Zhimomi",
    progress: 32,
  },
  {
    id: "p2",
    siteName: "Mokokchung Fuel Depot",
    status: "Active",
    currentPhase: "Monitoring",
    estimatedCompletion: "Dec 2026",
    consultant: "A. Longkumer",
    progress: 78,
  },
  {
    id: "p3",
    siteName: "Wokha Cement Yard",
    status: "On Hold",
    currentPhase: "Phytomining",
    estimatedCompletion: "Pending",
    consultant: "R. Kikon",
    progress: 45,
  },
  {
    id: "p4",
    siteName: "Chumukedima Warehouse Site",
    status: "Completed",
    currentPhase: "Closed out",
    estimatedCompletion: "Aug 2026",
    consultant: "T. Zhimomi",
    progress: 100,
  },
];

export const marketplaceProducts: MarketplaceProduct[] = [
  {
    id: "m1",
    name: "Pleurotus ostreatus Culture",
    category: "Mycoremediation",
    description: "Lab-grown oyster mushroom spawn for hydrocarbon degradation trials.",
    price: "₹2,400",
    unit: "unit",
    availability: "Available",
    supplier: "Northeast Mycology Labs",
  },
  {
    id: "m2",
    name: "Brassica juncea Seed Stock",
    category: "Phytoremediation",
    description: "Certified Indian mustard seed for lead-focused phytomining cycles.",
    price: "₹680",
    unit: "kg",
    availability: "Available",
    supplier: "Himalayan Agri Seeds",
  },
  {
    id: "m3",
    name: "Biochar Soil Amendment",
    category: "Soil Amendments",
    description: "High-porosity biochar for contaminant immobilization and pH buffering.",
    price: "₹1,150",
    unit: "50 kg bag",
    availability: "Available",
    supplier: "Terra Firma Amendments",
  },
  {
    id: "m4",
    name: "Portable XRF Soil Analyzer",
    category: "Monitoring Equipment",
    description: "Handheld heavy-metal screening unit for field verification.",
    price: "₹1.8L",
    unit: "unit",
    availability: "Limited Stock",
    supplier: "Vantage Field Instruments",
  },
  {
    id: "m5",
    name: "Pteris vittata Nursery Stock",
    category: "Phytoremediation",
    description: "Greenhouse-raised Chinese brake fern for arsenic hyperaccumulation.",
    price: "₹340",
    unit: "sapling",
    availability: "Made to Order",
    supplier: "Assam Wetland Nursery",
  },
  {
    id: "m6",
    name: "ISO 17025 Soil Panel",
    category: "Laboratory Services",
    description: "Full contaminant profiling with certified chain of custody.",
    price: "₹9,500",
    unit: "sample",
    availability: "Available",
    supplier: "Kohima Reference Laboratory",
  },
];

export const allSoilReports: SoilReport[] = [
  ...recentReports,
  {
    id: "r6",
    analysisId: "PS-20421",
    siteName: "Chumukedima Warehouse Site",
    soilType: "Sandy",
    contaminants: ["Petroleum hydrocarbons"],
    toxicity: "Moderate",
    status: "Monitoring",
    updatedLabel: "1 week ago",
    consultant: "A. Longkumer",
  },
  {
    id: "r7",
    analysisId: "PS-20409",
    siteName: "Zunheboto Quarry Site",
    soilType: "Mixed / Fill",
    contaminants: ["Cadmium", "Chromium"],
    toxicity: "Critical",
    status: "Draft",
    updatedLabel: "1 week ago",
    consultant: "T. Zhimomi",
  },
  {
    id: "r8",
    analysisId: "PS-20390",
    siteName: "Tuensang Transport Yard",
    soilType: "Peaty",
    contaminants: ["Diesel", "Benzene"],
    toxicity: "Moderate",
    status: "Blueprint Ready",
    updatedLabel: "2 weeks ago",
    consultant: "R. Kikon",
  },
];

export const commonContaminants = [
  "Lead",
  "Arsenic",
  "Cadmium",
  "Diesel",
  "Petroleum hydrocarbons",
  "Benzene",
  "Chromium",
];
